In [47]:
import networkx as nx
import pandas as pd

from keras.models import Sequential
from keras.layers import Dense

In [48]:
# FUNCTIONS
def attach_attributes(graph):
    degree_centralities = nx.degree_centrality(graph)
    betweenness_centralities = nx.betweenness_centrality(graph)
    closeness_centralities = nx.closeness_centrality(graph)
    pageranks = nx.pagerank(graph)

    for node_id in graph.nodes:
        node_attributes = {
            'degree_centrality': degree_centralities[node_id],
            'betweenness_centrality': betweenness_centralities[node_id],
            'closeness_centrality': closeness_centralities[node_id],
            'pagerank': pageranks[node_id]
        }
        graph.node[node_id].update(node_attributes)
        
def get_attributes(node_attributes, prefix):
    attributes_dict = {
        prefix + key: value
        for key, value in node_attributes
    }
    return attributes_dict


def graph_to_training_set(graph):
    adj_matrix = nx.adjacency_matrix(graph)
    idxs = range(adj_matrix.shape[0])
    rows = []
    for node1_id in idxs:
        attrs1 = get_attributes(graph.node[node1_id].items(), 'node1_')
        for node2_id in idxs:
            attrs2 = get_attributes(graph.node[node2_id].items(), 'node2_')
            row = {
                'num_of_conn': adj_matrix[node1_id, node2_id]
            }
            row.update(attrs1)
            row.update(attrs2)
            rows.append(row)
    return rows

In [49]:
n1, p1 = 10, 0.8

graph1 = nx.gnp_random_graph(n1, p1, seed=93)
attach_attributes(graph1)

graph1_data = graph_to_training_set(graph1)
df = pd.DataFrame(graph1_data)
df.head(20)

node1_betweenness_centrality  node1_closeness_centrality  \
0                       0.065079                    0.900000   
1                       0.065079                    0.900000   
2                       0.065079                    0.900000   
3                       0.065079                    0.900000   
4                       0.065079                    0.900000   
5                       0.065079                    0.900000   
6                       0.065079                    0.900000   
7                       0.065079                    0.900000   
8                       0.065079                    0.900000   
9                       0.065079                    0.900000   
10                      0.038690                    0.818182   
11                      0.038690                    0.818182   
12                      0.038690                    0.818182   
13                      0.038690                    0.818182   
14                      0.038690                    0.818182   
15                      0.038690                    0.818182   
16                      0.038690                    0.818182   
17                      0.038690                    0.818182   
18                      0.038690                    0.818182   
19                      0.038690                    0.818182   

    node1_degree_centrality  node1_pagerank  node2_betweenness_centrality  \
0                  0.888889        0.115981                      0.065079   
1                  0.888889        0.115981                      0.038690   
2                  0.888889        0.115981                      0.028042   
3                  0.888889        0.115981                      0.020437   
4                  0.888889        0.115981                      0.042659   
5                  0.888889        0.115981                      0.062765   
6                  0.888889        0.115981                      0.003968   
7                  0.888889        0.115981                      0.003968   
8                  0.888889        0.115981                      0.032011   
9                  0.888889        0.115981                      0.007937   
10                 0.777778        0.102944                      0.065079   
11                 0.777778        0.102944                      0.038690   
12                 0.777778        0.102944                      0.028042   
13                 0.777778        0.102944                      0.020437   
14                 0.777778        0.102944                      0.042659   
15                 0.777778        0.102944                      0.062765   
16                 0.777778        0.102944                      0.003968   
17                 0.777778        0.102944                      0.003968   
18                 0.777778        0.102944                      0.032011   
19                 0.777778        0.102944                      0.007937   

    node2_closeness_centrality  node2_degree_centrality  node2_pagerank  \
0                     0.900000                 0.888889        0.115981   
1                     0.818182                 0.777778        0.102944   
2                     0.818182                 0.777778        0.102355   
3                     0.818182                 0.777778        0.102099   
4                     0.900000                 0.888889        0.115496   
5                     0.900000                 0.888889        0.116046   
6                     0.642857                 0.444444        0.064424   
7                     0.692308                 0.555556        0.076688   
8                     0.900000                 0.888889        0.114905   
9                     0.750000                 0.666667        0.089062   
10                    0.900000                 0.888889        0.115981   
11                    0.818182                 0.777778        0.102944   
12                    0.818182                 0.777778        0.1

In [50]:
X_train = df.iloc[:, :8]
y_train = df.iloc[:, 8]

model = Sequential()
model.add(Dense(units=8, input_dim=8, activation='sigmoid'))
model.add(Dense(units=1))

model.compile(loss='binary_crossentropy', optimizer='sgd')

In [51]:
model.fit(X_train, y_train, epochs=100)

Epoch 1/100
100/100 [==============================] - 0s 459us/step - loss: 10.9603
Epoch 2/100
100/100 [==============================] - 0s 34us/step - loss: 10.9603
Epoch 3/100
100/100 [==============================] - 0s 32us/step - loss: 10.9603
Epoch 4/100
100/100 [==============================] - 0s 31us/step - loss: 10.9603
Epoch 5/100
100/100 [==============================] - 0s 33us/step - loss: 10.9603
Epoch 6/100
100/100 [==============================] - 0s 30us/step - loss: 10.9603
Epoch 7/100
100/100 [==============================] - 0s 33us/step - loss: 10.9603
Epoch 8/100
100/100 [==============================] - 0s 44us/step - loss: 10.9603
Epoch 9/100
100/100 [==============================] - 0s 28us/step - loss: 10.9603
Epoch 10/100
100/100 [==============================] - 0s 30us/step - loss: 10.9603
Epoch 11/100
100/100 [==============================] - 0s 33us/step - loss: 10.9603
Epoch 12/100
100/100 [==============================] - 0s 32us/step - lo

100/100 [==============================] - 0s 35us/step - loss: 10.9603
Epoch 98/100
100/100 [==============================] - 0s 36us/step - loss: 10.9603
Epoch 99/100
100/100 [==============================] - 0s 33us/step - loss: 10.9603
Epoch 100/100
100/100 [==============================] - 0s 40us/step - loss: 10.9603


In [52]:
# NEW
import numpy as np
import pandas as pd
import networkx as nx

# utwórz pusty graf zawierający tyle samo wierzchołków co graf początkowy
new_graph = nx.empty_graph(n=graph1.number_of_nodes())

# ustal liczbę krawędzi tworzonych przez każdy wierzchołek
num_edges = 3

node_similarities = {}

for u in graph1.nodes:
    # słownik zawierający, dla każdego wierzchołka, listę rankingową pozostałych wierzchołków
    node_similarities[u] = []

    for v in graph1.nodes:

        # pobierz cechy obu wierzchołków w parze
        d = {}
        d.update(get_attributes(graph1.nodes[u].items(),'node1_'))
        d.update(get_attributes(graph1.nodes[v].items(),'node2_'))
        
        # zamień cechy obu wierzchołków na format akceptowalny przez keras
        feature_values = pd.DataFrame([d], columns=d.keys())

        # dodaj do słownika wynikowego pary (wierzchołek, prawdopodobieństwo istnienia krawędzi)
        node_similarities[u].append((v,model.predict(feature_values)[0][0]))

# n-ta liczba harmoniczna (str. 4 artykułu o priority rank), suma 1/1+1/2+1/3+...+1/n
h_n = sum([1/k for k in range(1,graph1.number_of_nodes()+1)])

for u in graph1.nodes:
    # dla każdego wierzchołka posortuj pozostałe wierzchołki w malejącym porządku prawdopodobieństwa krawędzi
    ranking = [n for (n, sim) in sorted(node_similarities[u], key=lambda x: x[1], reverse=True)]

    # wylicz prawdopodobieństwo utworzenia krawędzi do wierzchołka na danej pozycji rankingu
    # wzór 1 na str.4 artykułu o priority rank
    prob = [1/(idx * h_n) for idx, elem in enumerate(ranking, start=1)]

    # wylosuj k wierzhołków do których bieżący wierzchołek u tworzy krawędzie
    target_nodes = np.random.choice(ranking, size=num_edges, replace=False, p=prob)

    # dodaj krawędzie w generowanym grafie
    for tn in target_nodes:
        new_graph.add_edge(u, tn)

print(nx.adj_matrix(new_graph).todense())

[[0 1 0 0 0 0 1 1 0 1]
 [1 1 0 1 0 0 0 0 1 1]
 [0 0 1 0 0 0 1 1 0 0]
 [0 1 0 0 1 1 1 1 1 1]
 [0 0 0 1 0 1 0 1 0 1]
 [0 0 0 1 1 0 0 1 0 1]
 [1 0 1 1 0 0 0 1 1 1]
 [1 0 1 1 1 1 1 1 1 0]
 [0 1 0 1 0 0 1 1 0 0]
 [1 1 0 1 1 1 1 0 0 0]]
